[package]
name = "Zlack"
version = "1.1.2"
description = "A lightweight Slack desktop client built with Tauri"
authors = ["sanguneo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
lazy_static = "1.5.0"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-notification = "2"
tauri-plugin-shell = "2"
tauri-plugin-single-instance = { version = "2" }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
core-graphics = "0.25.0"
objc2 = "0.6.4"

[target.'cfg(windows)'.dependencies]
tauri-winrt-notification = "0.7.2"
windows = { version = "0.48", features = ["Win32_System_Com"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
